'use server'
import { z } from 'zod'
import crypto from 'node:crypto'
import { createClient } from '@/shared/db/server'
import { requireOfficeStaff } from '@/shared/auth-helpers/require'
import { getCurrentClaims } from '@/shared/auth-helpers/claims'
import { logAuditEvent } from '@/shared/audit'
import type { Database } from '@/shared/db/types'

// Source: docs/DESIGN.md §3.3 jobs table; CLAUDE.md hidden invariants.
//
// CRITICAL INVARIANTS:
//   1. jobs.production_status is REVOKE'd from authenticated. Status transitions go ONLY
//      through app.record_scan_event() (Phase 3 / scanning module). UpdateJobSchema
//      MUST NOT include production_status.
//   2. job_number is generated by app.next_job_number() RPC. The RPC reads tenant_id
//      from the JWT — never accept tenant_id as a parameter.
//   3. packet_token is 16-char URL-safe random; persists across packet reprints.
//   4. intake_status='in_production' requires production_status set; we leave that
//      transition to scanning. Caller can move draft→scheduled freely.

type JobUpdatePayload = Database['public']['Tables']['jobs']['Update']

function generatePacketToken(): string {
  return crypto.randomBytes(16).toString('base64url').slice(0, 16)
}

const PrioritySchema = z.enum(['low', 'normal', 'high', 'rush'])
const IntakeStatusSchema = z.enum(['draft', 'scheduled', 'archived'])
// Note: 'in_production' intentionally excluded — that transition is owned by scanning module.

const CreateJobSchema = z.object({
  company_id: z.string().uuid(),
  contact_id: z.string().uuid().nullish(),
  job_name: z.string().min(1).max(200),
  description: z.string().max(20000).nullish(),
  customer_po_number: z.string().max(100).nullish(),
  part_count: z.number().int().min(0).nullish(),
  weight_lbs: z.number().nonnegative().nullish(),
  dimensions_text: z.string().max(200).nullish(),
  color: z.string().max(100).nullish(),
  coating_type: z.string().max(100).nullish(),
  due_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullish(),
  priority: PrioritySchema.optional(),
  intake_status: IntakeStatusSchema.optional(),
  quoted_price: z.number().nonnegative().nullish(),
  notes: z.string().max(20000).nullish(),
  parent_job_id: z.string().uuid().nullish(),
})

export type CreateJobInput = z.infer<typeof CreateJobSchema>

const UpdateJobSchema = CreateJobSchema.partial().extend({
  id: z.string().uuid(),
})

export type UpdateJobInput = z.infer<typeof UpdateJobSchema>

const HoldJobSchema = z.object({
  id: z.string().uuid(),
  on_hold: z.boolean(),
  hold_reason: z.string().max(500).optional(),
})

const ArchiveJobSchema = z.object({ id: z.string().uuid() })

interface JobRow {
  id: string
  tenant_id: string
  job_number: string
  packet_token: string
}

export async function createJob(input: unknown): Promise<JobRow> {
  const parsed = CreateJobSchema.safeParse(input)
  if (!parsed.success) throw new Error('Invalid input')

  await requireOfficeStaff()
  const claims = await getCurrentClaims()
  const supabase = await createClient()

  // Step 1: get atomic tenant-scoped job_number from server-side RPC.
  // app.next_job_number lives in the `app` schema, which isn't included in the
  // generated Database type (gen-types only emits public). Narrow-cast around it.
  type AppRpc<TResult> = (fn: string) => Promise<{ data: TResult | null; error: { message: string } | null }>
  const callAppRpc = supabase.rpc as unknown as AppRpc<string>
  const { data: jobNumber, error: numberError } = await callAppRpc('next_job_number')
  if (numberError || !jobNumber) {
    throw new Error(`Job number generation failed: ${numberError?.message ?? 'unknown'}`)
  }

  // Step 2: insert.
  const packet_token = generatePacketToken()
  const { data, error } = await supabase
    .from('jobs')
    .insert({
      tenant_id: claims.tenant_id,
      job_number: jobNumber as string,
      packet_token,
      company_id: parsed.data.company_id,
      contact_id: parsed.data.contact_id ?? null,
      job_name: parsed.data.job_name,
      description: parsed.data.description ?? null,
      customer_po_number: parsed.data.customer_po_number ?? null,
      part_count: parsed.data.part_count ?? null,
      weight_lbs: parsed.data.weight_lbs ?? null,
      dimensions_text: parsed.data.dimensions_text ?? null,
      color: parsed.data.color ?? null,
      coating_type: parsed.data.coating_type ?? null,
      due_date: parsed.data.due_date ?? null,
      priority: parsed.data.priority ?? 'normal',
      intake_status: parsed.data.intake_status ?? 'draft',
      quoted_price: parsed.data.quoted_price ?? null,
      notes: parsed.data.notes ?? null,
      parent_job_id: parsed.data.parent_job_id ?? null,
      created_by_staff_id: claims.staff_id ?? null,
    })
    .select('id, tenant_id, job_number, packet_token')
    .single()

  if (error || !data) throw new Error(`Job insert failed: ${error?.message ?? 'unknown'}`)

  await logAuditEvent({ action: 'create', entity_type: 'job', entity_id: data.id })
  return data
}

export async function updateJob(input: unknown): Promise<{ id: string }> {
  const parsed = UpdateJobSchema.safeParse(input)
  if (!parsed.success) throw new Error('Invalid input')

  await requireOfficeStaff()
  const supabase = await createClient()

  const { id, ...patch } = parsed.data
  const updateRow = Object.fromEntries(
    Object.entries(patch).filter(([, value]) => value !== undefined)
  ) as JobUpdatePayload

  // Defense in depth: even though z schema excludes production_status,
  // a future schema change might re-add it. Strip again here.
  if ('production_status' in updateRow) delete updateRow.production_status

  const { error } = await supabase.from('jobs').update(updateRow).eq('id', id)
  if (error) throw new Error(`Job update failed: ${error.message}`)

  await logAuditEvent({
    action: 'update',
    entity_type: 'job',
    entity_id: id,
    changed_fields: updateRow as Record<string, unknown>,
  })
  return { id }
}

export async function setJobHold(input: unknown): Promise<{ id: string; on_hold: boolean }> {
  const parsed = HoldJobSchema.safeParse(input)
  if (!parsed.success) throw new Error('Invalid input')
  if (parsed.data.on_hold && !parsed.data.hold_reason) {
    throw new Error('Invalid input: hold_reason required when on_hold=true')
  }

  await requireOfficeStaff()
  const supabase = await createClient()

  const { error } = await supabase
    .from('jobs')
    .update({
      on_hold: parsed.data.on_hold,
      hold_reason: parsed.data.on_hold ? (parsed.data.hold_reason ?? null) : null,
    })
    .eq('id', parsed.data.id)

  if (error) throw new Error(`Job hold update failed: ${error.message}`)

  await logAuditEvent({
    action: 'update',
    entity_type: 'job',
    entity_id: parsed.data.id,
    changed_fields: { on_hold: parsed.data.on_hold, hold_reason: parsed.data.hold_reason },
  })
  return { id: parsed.data.id, on_hold: parsed.data.on_hold }
}

export async function archiveJob(input: unknown): Promise<{ id: string }> {
  const parsed = ArchiveJobSchema.safeParse(input)
  if (!parsed.success) throw new Error('Invalid input')

  await requireOfficeStaff()
  const supabase = await createClient()

  const { error } = await supabase
    .from('jobs')
    .update({ archived_at: new Date().toISOString(), intake_status: 'archived' })
    .eq('id', parsed.data.id)

  if (error) throw new Error(`Job archive failed: ${error.message}`)

  await logAuditEvent({ action: 'archive', entity_type: 'job', entity_id: parsed.data.id })
  return { id: parsed.data.id }
}
